# Generated by Django 4.2.6 on 2023-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('ticket_id', models.CharField(max_length=50)),
                ('ticket_reference', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('card_id', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('route_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
